### PR TITLE
Docs improvements

### PR DESCRIPTION
**Pull request by oskarkk**
I've added:
 - `playerclass` and `duty` commands (`duty` is related to shortcuts feature, I'm not sure if it works today)
 - permissions for specific commands
 - more info on spawns

And fixed some small things.

### CODE REVIEW

**Comment by Oruss7** [comment]
I'm not sure if it's a good idea to document `duty` as nobody know how it works (and if it's working).

**Comment by Eredrim** [comment]
Duty works but is quite useless. It enables possibility to become admin of PVPArena temporarily but it needs to already be an admin or have a dedicated permission. In few words, it is as easier to do it as with your permission plugin. I agree with Oruss7, it would be better if it was removed. Additionally, can you squash your commits please and prefix the message with [doc] (without ending "s")?

**Comment by oskarkk** [comment]
Okay, I'll do it. As for the duty command, I'm not sure if it makes you an admin, but I'm sure that it somehow disables functionality of shortcuts (if they are enabled and iirc only-shortcuts is true). I put it in the doc because I think it's better to have docs pointing it to an undocumented (maybe broken) feature, than just have it in the plugin without any explanation (it shows up in tab completions). 

I tried to understand what is the purpose of shortcuts and I think it was for something like batch editing of arenas (quite useful I'd say), but I couldn't get it to do anything correctly, so I'm like 75% sure it's broken. And I found the commit which introduces this feature and it's described as "for arena management" which supports my theory. Also, it referenced some issue numbers, but the original slipcor's repo doesn't have issues.

**Comment by Eredrim** [comment]
I share you opinion about shortcuts and I think this feature is completely broken and should be removed.
Concerning Slipcor's issues page, it existed but that page is now closed (and removed) to avoid people creating issues in the bad place. Unfortunately, GitHub doesn't provide a feature giving a read-only access to issue pages...

In any cases, I merge your request, thanks for your help 👍

**Pull request merged**
